vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /brochures
           upload_destination: '%kernel.project_dir%/public/brochures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
